### ISSUE TITLE
Not Getting any call back.

### ISSUE THREAD

**Issue by SachinCodeMatrix** [GJJ2019/easy_upi_payment#13]
type 'Null' is not a subtype of type 'String' in type cast

Getting this exception always. Even though the transaction is a success, we are getting an exception.

**Comment by SachinCodeMatrix** [comment]
Basically, i am not getting  any response after payment is processed.
It always has below exception.
type 'Null' is not a subtype of type 'String' in type cast

**Comment by GJJ2019** [comment]
is there logs present. I tried payment its working for me

**Comment by SachinCodeMatrix** [comment]
@GJJ2019  Payment is working but not getting status.

**Comment by GJJ2019** [comment]
Can u plz try again & send me the logs from vs-code or AS

**Comment by SachinCodeMatrix** [comment]
Hello @GJJ2019  Here is the logs

W/EasyUpiPayment(22474): Current Activity isn't AppCompatActivity.
W/EasyUpiPayment(22474): You'll need to call EasyUpiPayment#detachListener() to remove listener.
I/flutter (22474): exeption
I/flutter (22474): type 'Null' is not a subtype of type 'String' in type cast

**Comment by muhd-ameen** [comment]
D/PaymentUiActivity( 5512): Payment Response is null

i got this as in log

**Comment by muhd-ameen** [comment]
i used google pay

**Comment by muhd-ameen** [comment]
I manually edited the TransactionDetailModel variables to dynamic data type, and it returns the  details now

**Comment by SachinCodeMatrix** [comment]
@muhd-ameen Are u getting correct status?

**Comment by SachinCodeMatrix** [comment]
@muhd-ameen  can u please put the response once here?

**Comment by muhd-ameen** [comment]
transactionDetailModel.approvalRefNo is getting null from the response
All the other parameter as string

@GJJ2019
