### ISSUE TITLE
 error: cannot access PaymentStatusListener

### ISSUE THREAD

**Issue by grit-ameen** [GJJ2019/easy_upi_payment#15]
D:\project\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: cannot access PaymentStatusListener
      flutterEngine.getPlugins().add(new com.pcu.easy_upi_payment.EasyUpiPaymentPlugin());
                                ^
  class file for dev.shreyaspatil.easyupipayment.listener.PaymentStatusListener not found
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by GJJ2019** [comment]
Yes Im checking on this

**Comment by muhd-ameen** [comment]
thanks for your attention, i ran your example project it also have same issue

**Comment by GJJ2019** [comment]
@muhd-ameen  @grit-ameen  try adding ```implementation "dev.shreyaspatil.EasyUpiPayment:EasyUpiPayment:3.0.3"```
in your ```android/build.gradle```

**Comment by muhd-ameen** [comment]
@GJJ2019 Thanks for the support, it worked...😍😍

but have an issue of application crashing with a device with no UPI apps.
