### ISSUE TITLE
is after payment 

### ISSUE THREAD

**Issue by sanjay12340** [GJJ2019/easy_upi_payment#16]
approvalRefNo: data['approvalRefNo'] as String, while payment using phone pe , google pay ,but paytm woking file

**Comment by muhd-ameen** [comment]
@sanjay12340 have you got the response details from this package like 'Payment response', 'Payment amount', 'Payment transactionId, 'Payment transactionRefId',  anything returned from this package? 
Please help

Thanks in advance,

**Comment by shajin-sha** [comment]
@muhd-ameen Hi, does this packages works now? for you?

Thanks in advance.

**Comment by muhd-ameen** [comment]
> @muhd-ameen Hi, does this packages works now? for you?
> 
> 
> 
> Thanks in advance.

yes, i made some changes in the details model in package then it works for me @sanjay12340

**Comment by GJJ2019** [comment]
fixed in v0.1.4

**Comment by shajin-sha** [comment]
> > @muhd-ameen Hi, does this packages works now? for you?
> > Thanks in advance.
> 
> yes, i made some changes in the details model in package then it works for me

And only for merchant UPI id right?

**Comment by muhd-ameen** [comment]
> > > @muhd-ameen Hi, does this packages works now? for you?
> > > Thanks in advance.
> > 
> > 
> > yes, i made some changes in the details model in package then it works for me
> 
> And only for merchant UPI id right?

yes, upi payment only works for merchant UPI's

**Comment by shajin-sha** [comment]
If you do't mind can I ask one more question...?

Who needs  merchant UPI? 

- Someone who receives payment
- Someone who sent payment

Who?
