### ISSUE TITLE
Payment is failing after some transactions

### ISSUE THREAD

**Issue by SachinCodeMatrix** [GJJ2019/easy_upi_payment#19]
Getting this message from all upi apps. and transaction is getting failed 

![Screenshot_2023-05-26-21-40-54-120_com phonepe app](https://github.com/GJJ2019/easy_upi_payment/assets/80881563/18b4fe98-3510-4ed1-b42e-d1d1e8caa524)

**Comment by GJJ2019** [comment]
I tried payment from example app its working fine. Please provide more logs

**Comment by SachinCodeMatrix** [comment]
It is working for me also. but after a few 5 -6 continuous transactions it is failing.

**Comment by GJJ2019** [comment]
I'm not sure but it maybe from npci side for some security reasons

**Comment by GJJ2019** [comment]
can u check this repo if there's any similar issue https://github.com/PatilShreyas/EasyUpiPayment-Android

**Comment by GJJ2019** [comment]
closing this issue

**Comment by SachinCodeMatrix** [comment]
@GJJ2019  is fixed?

**Comment by GJJ2019** [comment]
Its not in the scope of this plugin maybe research some more you will find solution

**Comment by SachinCodeMatrix** [comment]
@GJJ2019 Is there any idea why transaction is failing on the same?

**Comment by GJJ2019** [comment]
> I'm not sure but it maybe from npci side for some security reasons

this
