### ISSUE TITLE
Payment Declined 

### ISSUE THREAD

**Issue by SanketKarwa24** [GJJ2019/easy_upi_payment#22]
I have tried payment using GPay, PhonePe, Paytm
Unable to do payment with all three payment gateway.

![processed-ab386a36-d3aa-44d8-a9e8-acbafe1d6549_4Jt922zV](https://github.com/GJJ2019/easy_upi_payment/assets/88473839/aac438dd-0ec6-4599-9353-911e7b8e4d9f)

**Comment by GJJ2019** [comment]
Im not sure why payment is getting declined try to research on this repo https://github.com/PatilShreyas/EasyUpiPayment-Android

**Comment by SanketKarwa24** [comment]
@GJJ2019 Is it mandatory to use business account id and merchant code ?

**Comment by GJJ2019** [comment]
I'm not sure u might need to do some research on your own plz comment below if u find anything

**Comment by krishnaji-yedlapalli** [comment]
Any update on this issue?
