### ISSUE TITLE
Payment Failed

### ISSUE THREAD

**Issue by ChinmayaGit** [GJJ2019/easy_upi_payment#25]
i am always getting 24 hour payment limit exceeded. i tried every bank same issue every day.
![WIN_20230801_15_23_57_Pro](https://github.com/GJJ2019/easy_upi_payment/assets/86422995/13d006e3-8c08-4ab9-9958-b9a7c345bc3a)

**Comment by GJJ2019** [comment]
This issue is not from this plugin kindly do some research or contact your bank for clarification
