### ISSUE TITLE
Payment Declining due to security reasons

### ISSUE THREAD

**Issue by krishnaji-yedlapalli** [GJJ2019/easy_upi_payment#26]
Getting below issue, after entering the UPI, any soultion for this?
![image](https://github.com/GJJ2019/easy_upi_payment/assets/49545948/c4aa99c7-9d70-4b7a-a18a-698ffa2e58b4)

**Comment by GJJ2019** [comment]
This plugin is only wrapper for flutter (android apps) kindly post issue [here](https://github.com/PatilShreyas/EasyUpiPayment-Android)
