### ISSUE TITLE
Transaction Failed

### ISSUE THREAD

**Issue by bhaumikwallis** [GJJ2019/easy_upi_payment#27]
I have used this plugin but i when i have transaction to bank limit issue how can i solve this issue ?

**Comment by GJJ2019** [comment]
not sure about this issue but look like issue with bank or upi id

**Comment by GJJ2019** [comment]
just google things if something need to be in plugin let me know

**Comment by bhaumikwallis** [comment]
i have use my live upi and other upi check but same issue facing in bank limit exidded transaction not success.
