### ISSUE TITLE
 Production Mode?

### ISSUE THREAD

**Issue by BLACKCAT25896** [GJJ2019/easy_upi_payment#28]
Its default Test Mode how to make it Production Mode?

**Comment by GJJ2019** [comment]
what do u mean ?

**Comment by BLACKCAT25896** [comment]
when i testing its says testing payment . i want it live payment

**Comment by GJJ2019** [comment]
yeah just pass parameter (desc title etc)  according to your need

**Comment by BLACKCAT25896** [comment]
![IMG-20231124-WA0017](https://github.com/GJJ2019/easy_upi_payment/assets/18536121/3193afda-8484-48ad-b4f1-b14e1ee2bbe5)
its shows testing. i need actual transaction

**Comment by GJJ2019** [comment]
yes u can just change description it will work fine

**Comment by GJJ2019** [comment]
https://github.com/GJJ2019/easy_upi_payment/blob/73fa84850e0c4bebd26016e8356dd03b21795422/example/lib/app/features/main/view/main_view.dart#L241

**Comment by BLACKCAT25896** [comment]
description is mendatory?
