### ISSUE TITLE
Facing "Your money has not been debited......."

### ISSUE THREAD

**Issue by shahrukh-vaikunth** [GJJ2019/easy_upi_payment#3]
I'm facing following issue while testing upi transaction using easy_upi_payment library. Please check below screenshot for more details.

![WhatsApp Image 2022-08-08 at 3 41 25 PM](https://user-images.githubusercontent.com/107293503/183395318-6c045a0a-750d-48ea-93c9-b3470cbac682.jpeg)

Any help would be appreciable.

Thank you

**Comment by GJJ2019** [comment]
Its not an issue from plugin side I think its something to do with google pay app as for other apps its not showing that message

**Comment by rohankokkulabp** [comment]
@GJJ2019 
I downloaded the apk from the README.md, facing the same issue with GooglePay and Paytm
