### ISSUE TITLE
This upi is working (redgorillas@icici) and multiple another upi i tried but payment is not success using this plugin please try to understand and upgrade 

### ISSUE THREAD

**Issue by umangdinjan** [GJJ2019/easy_upi_payment#32]

**Comment by Prashant4900** [comment]
@umangdinjan I also face the same problem it successfully redirects to the UPI App with the correct UPI number but after after entering the UPI pin, it shows an error because of security reasons your payment is not initiated something like this.

**Comment by umangdinjan** [comment]
yeah 

> @umangdinjan I also face the same problem it successfully redirects to the UPI App with the correct UPI number but after after entering the UPI pin, it shows an error because of security reasons your payment is not initiated something like this.

**Comment by GJJ2019** [comment]
This was just a wrapper around https://github.com/PatilShreyas/EasyUpiPayment-Android & its un maintain now :(

**Comment by umangdinjan** [comment]
easy_upi_payment: ^0.1.6 

this package also used and facing same issue try to another upi id is not working showing me error and i am working on only in flutter not in android so try to guide me with flutter

**Comment by umangdinjan** [comment]
> This was just a wrapper around https://github.com/PatilShreyas/EasyUpiPayment-Android & its un maintain now :(


easy_upi_payment: ^0.1.6

this package also used and facing same issue try to another upi id is not working showing me error and i am working on only in flutter not in android so try to guide me with flutter

**Comment by umangdinjan** [comment]
easy_upi_payment: ^0.1.6

this package also used and facing same issue try to another upi id is not
working showing me error and i am working on only in flutter not in android
so try to guide me with flutter
