### ISSUE TITLE
Other UPI ID in not working  Showing me error at last moment

### ISSUE THREAD

**Issue by umangdinjan** [GJJ2019/easy_upi_payment#33]
this package also used and facing same issue try to another upi id is not
working showing me error and i am working on only in flutter not in android
so try to guide me with flutter

**Comment by GJJ2019** [comment]
I cant do much in this situation with my limited time :( try using upi_pay plugin

**Comment by umangdinjan** [comment]
Around 3 years ago this plugin updated now i tried this but api is deperecated so this one not running project in flutter
