### ISSUE TITLE
Please Solve this problem

### ISSUE THREAD

**Issue by devendra257** [GJJ2019/easy_upi_payment#34]
![photo_6080344979034717006_y](https://github.com/GJJ2019/easy_upi_payment/assets/141297341/f61c9259-88c6-4ed5-816b-6931a7f8ba02)
Please Solve this problem sir

**Comment by GJJ2019** [comment]
I think its better to switch to another plugin as this been archive - https://github.com/PatilShreyas/EasyUpiPayment-Android
