### ISSUE TITLE
This plugin can't make payment always payment error.

### ISSUE THREAD

**Issue by gitcoder-23** [GJJ2019/easy_upi_payment#35]
![Screenshot_20240412_212254](https://github.com/GJJ2019/easy_upi_payment/assets/68274519/7f93687c-f524-4946-9d3d-f2a657255ac3)

**Comment by GJJ2019** [comment]
this plugin is archived & stop updating [EasyUpiPayment-Android](https://github.com/PatilShreyas/EasyUpiPayment-Android)

i'll try to find alternative

**Comment by gitcoder-23** [comment]
Yes please. I need the alternative option because my application has already finished but I stuck in this last option to make payments.

**Comment by GJJ2019** [comment]
I really rec to use other dep as this might take some time

**Comment by gitcoder-23** [comment]
Ok sure. Thank you. And please update me.
Because I used already upi_india same issue in it as like the easy_upi_payment
