### ISSUE TITLE
Getting error on making a payment

### ISSUE THREAD

**Issue by Anshulverma33** [GJJ2019/easy_upi_payment#37]
![WhatsApp Image 2024-06-06 at 6 01 59 PM](https://github.com/GJJ2019/easy_upi_payment/assets/43145798/0f835706-3d9e-4718-b946-0d9e8464ceae)

Getting error when doing payments Any suggestion..........

**Comment by GJJ2019** [comment]
Apps like Google Pay, PhonePe, and Paytm might not be able to complete your transaction right now. They could show errors like "Maximum limit exceeded" or "Risk threshold exceeded." This could happen if you're trying to send money to someone's personal UPI (Unified Payments Interface) account. Another reason could be that you've reached the maximum number of transactions allowed for the day. In this case, you may need to wait until tomorrow to try the same transaction again.

Note: Remember to use only business UPI accounts. You can't send money to personal UPI accounts. Stick to business accounts for your transactions.
