### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MominRaza** [GJJ2019/easy_upi_payment#6]
I try with GPay and PhonePe, both not working. I also try to pay to your UPI id but not working.

**Comment by MominRaza** [comment]
also paytm not working

**Comment by GJJ2019** [comment]
I'm currently using it for my application it's working fine

**Comment by techcafe13** [comment]
NOT WORKING>>

**Comment by GJJ2019** [comment]
@techcafe13 please provide more details whats not working or what i can do to help you

**Comment by MominRaza** [comment]
@GJJ2019 please tell which merchant upi you are using

**Comment by GJJ2019** [comment]
I have just tested with my upi id & its working fine in my application as well if u need more details please visit this repo - https://github.com/PatilShreyas/EasyUpiPayment-Android
